[config]
version_check = false
reload_apps = true

[config.reload_apps_list]
gtk_theme = true

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk-colors.css" 
output_path = "~/.config/gtk-3.0/colors.css"
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark'

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/gtk-4.0/colors.css"
